name: CommandSigns
main: co.nz.LolNet.commandsigns.CommandSigns
authors: [GhostHack] 
version: 1.0
description: >
             uses signs to run commands then right clicked.
depend: [Vault]
softdepend: [Multiverse-Core]
commands:
  commandsigns:
    aliases: [cmdsign]
    description: CommandSigns commands.
    usage: |
        /cmdsign <linenumber> <text>
               Add a line with one command or a line of text to the clipboard.
        /ccmdsign batch
               Changes your state into batch mode for doing bigger tasks quicker.
        /cmdsign clear
               Clear your CommandSigns clipboard.
        /cmdsign copy
               Copy a CommandSign to clipboard (the command lines associated with it).
               Note: You need permission to create a sign in order to read.
        /cmdsign edit
               Edit a CommandSign in live mode.
        /cmdsign insert <linenumber> <text>
               Insert a line into an existing CommandSign.
               Changes are stored in clipboard: click a sign to apply.
        /cmdsign read
               Read a CommandSign (the command lines associated with it).
               Note: You need permission to create a sign in order to read.
        /cmdsign reload
               Reload CommandSigns.
        /cmdsign remove
               Remove a CommandSign.
        /commandsigns view
               View the contents of your clipboard.
permissions:
    commandsigns.*:
        description: Gives access to all CommandSigns commands
        children:
            commandsigns.create.*: true
            commandsigns.remove: true
            commandsigns.use.*: true
            commandsigns.group.*: true
            commandsigns.update: true
            commandsigns.save: true
            commandsigns.reload: true
            commandsigns.edit: true
        default: op
    commandsigns.create.*:
        description: Gives access CommandSigns sign creation commands
        children:
            commandsigns.create.regular: true
            commandsigns.create.super: true
            commandsigns.create.redstone: true
            commandsigns.create.op: true
    commandsigns.save:
        description: Allows saving CommandSigns without reloading
        default: false;
    commandsigns.reload:
        description: Reloads CommandSigns and all configuration
        default: false;
    commandsigns.use.*:
        description: Gives access to CommandSigns sign use
        default: true
        children:
            commandsigns.use.regular: true
            commandsigns.use.super: true
    commandsigns.create.regular:
        description: Allows you to create a regular CommandSign
        default: false
    commandsigns.create.super:
        description: Allows you to create a super CommandSign
        default: false
    commandisgns.create.op:
        description: Allows you to create op-level CommandSigns
        default: false
    commandsigns.remove:
        description: Allows you to remove a CommandSign
        default: false
    commandsigns.use.regular:
        description: Allows you to use a regular CommandSign
        default: false
    commandsigns.use.super:
        description: Allows you to use a super CommandSign
        default: false
    commandsigns.group.*:
        description: Allows you to use all group commands
        default: false
    commandsigns.edit:
        description: Allows editing of CommandSigns
        default: false