placeByPlayer:
  Global:
  world:
placeByPlayerDirectlyBelow:
  Global:
  world:
craftByPlayer:
  Global:
  world:
playerBlockInteract:
  Global:
  world:
playerRightClickItem:
  Global:
  world:
playerLeftClickItem:
  Global:
  world:
playerClickItemInventory:
  Global:
  world:
playerPickupItem:
  Global:
  world:
GlobalCraftBan:
  Global:
  world:
DisableNetherPortalCreation: false
  