placeByPlayer:
  Global:
  world:
placeByPlayerDirectlyBelow:
  Global:
  world:
craftByPlayer:
  Global:
  world:
playerBlockInteract:
  Global:
  world:
playerClickItemInventory:
  Global:
  world:
playerPickupItem:
  Global:
  world:
GlobalCraftBan:
  